name: Report reusing
description: Report a single paper reusing (parts) from other papers. 
title: "[Reusing]: "
labels: []
assignees: []
body: 
  - type: markdown
    attributes: 
      value: |
        Thank you for reporting research which is reusing other papers.  ![cheatsheet](https://raw.githubusercontent.com/bhermann/DoR/main/.github/ISSUE_TEMPLATE/report_reusing_cheatsheet.png)
  - type: input
    id: source_doi
    attributes: 
      label: DOI 
      description: The DOI of the paper to be inspected 
      placeholder: e.g. 10.1145/3368089.3409767
    validations:
      required: true